# Generated by Django 2.1.3 on 2018-11-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='TargetUser',
        ),
    ]
