# Generated by Django 2.1.3 on 2018-11-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_bot', '0002_auto_20181123_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetuser',
            name='fbid',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='targetuser',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
