# Generated by Django 2.1.3 on 2018-11-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_bot', '0003_auto_20181123_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbid', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
    ]
